name: 'CI setup'
runs:
  using: 'composite'
  steps:
    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
        registry-url: 'https://registry.npmjs.org'

    - name: Update npm registry
      run: npm run registry

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
