name: 'Publish Docs'
description: 'Publish Docs'
inputs:
  docker_username:
    description: "..."
    required: true
  docker_password:
    description: "..."
    required: true
  incubator_github_user:
    description: "..."
    required: true
  incubator_github_token:
    description: "..."
    required: true
runs:
  using: 'composite'
  steps:
    # - name: Declare some variables
    #   id: vars
    #   shell: bash
    #   run: |
    #     echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
    #     echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Set output
      shell: bash
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: baloise/design-system-docs:${{ steps.vars.outputs.sha_short }},baloise/design-system-docs:latest

    # - name: Deploy
    #   uses: addnab/docker-run-action@v3
    #   with:
    #     image: baloise/gitopscli:5.4.0
    #     run: |
    #       gitopscli deploy \
    #       --git-provider-url https://github.com \
    #       --username ${{ inputs.incubator_github_user }} \
    #       --password ${{ inputs.incubator_github_token }} \
    #       --git-user "Baloise Incubator" \
    #       --git-email "incubator@baloise.dev" \
    #       --organisation "baloise-incubator" \
    #       --repository-name "okd4-example-apps" \
    #       --file "baloise-design-system-docs-test/values.yaml" \
    #       --values "{designsystem.image.tag: ${{ steps.vars.outputs.sha_short }}}"
