name: Auto UX Testing checklist

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  CreateUXChecklist:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Check for /ux-checklist command
        id: ux-checklist
        uses: actions/github-script@v5
        with:
          script: |
            const comment = context.payload.comment.body;
            const prNumber = context.payload.issue.number;
            console.log(comment);
            console.log(prNumber);
